### ISSUE TITLE
Exception raised : portalocker.exceptions.LockException: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by alcoat** [shaypal5/cachier#128] opened 2023-12-03 21:54 UTC
https://github.com/python-cachier/cachier/blob/5776ee8d63c8a5719ccd3737f0f504bc1a7eb679/cachier/pickle_core.py#L145C67-L145C67

On linux system, the cache file seems to be closed twice. When replacing this part of code with:
                #with portalocker.Lock(fpath, mode='rb') as cache_file:
                cache_file = portalocker.Lock(fpath, mode='rb')
                if cache_file is not None:
                    try:
                        self.cache = pickle.load(open(cache_file.filename,"rb"))
                    except EOFError:
                        self.cache = {}
the  cachier seems to work fine.

**Comment by shaypal5** [comment] 2023-12-04 11:04
I'm sorry, that's not enough information to address the bug.

The package is tested and used on Linux, and this is the first report of such an issue. Also, you didn't explain in anyway how this hampers in any way use of the package.

Also, I would not move from a context manager - which is the correct and more safe way to lock a file - to a simple use of `Lock` without a much better explanation.

This is issue is marked with `wontfix` until the issue is shown to be reproducible on any Linux machine, and we get a better explanation of what you believe might be causing the redundant locking, the **negative effects** of this phenomena and possibly even a better suggestion for a fix (I can't see why portalocker's context manager will cause double locking but their `Lock` method will not).

**Comment by alcoat** [comment] 2023-12-04 11:27
I am not suggesting a solution with the modification on my first comment : this is really uggly and should not be used. However cachier is not usable for me at this time.

**Comment by alcoat** [comment] 2023-12-04 15:28
In fact it seems to be the same as #86 with NFS mount. When forcing the cache_dir on the local directory (like /tmp) everything is working

**Comment by alcoat** [comment] 2023-12-05 17:13
@lordjabez Yes, it works when you move the cache_dir to a local disk. Most of my apps are using NFS shares and do depend on a single computer. After looking for solutions, I found that it is not a problem with cachier but portalocker.
In fact I'm trying to use an app in which cachier is used on a network with share disk spaces

**Closed as not planned** 2023-12-05 17:14 UTC
Labels: bug, wontfix

**Comment by lordjabez** [comment] 2023-12-05 17:19
Perhaps you can create an issue with portalocker and link here? We can update the dependency when it's fixed?

**Comment by shaypal5** [comment] 2023-12-05 19:08
Great, I've responded in the `portalocker` issue you've created with a link to the first NFS-related issue. Let's see when does this gets solved.

**Comment by alcoat** [comment] 2023-12-05 19:36
[like]  Coat, Alain reacted to your message:
________________________________
