### ISSUE TITLE
Signature change does not invalidate cache on keyword arguments when matched by position

### ISSUE THREAD

**Issue by lorenzwalthert** [shaypal5/cachier#70] opened 2021-08-25 07:40 UTC
Thanks for this cool package, it saved so much of my time with zero hassle 🥳. Then, I edited some function definition in my code and re-ran my `.py` file. I found that the cache was not invalidated. Here is a reproducible example in one session that should show the same behavior I think. It shows:

1. Renaming arguments does not invalidate the cache.
2. Changing order or arguments does not invalidate the cache.
3. The same also appears when adding or removing arguments.

```python

from cachier import cachier

args = (1, 2)
@cachier()
def g(foo, bar):
    return 'bar'

print(g(*args))
#>>> bar

# let's change the argument name: bar -> bars
@cachier()
def g(foo, bars):
    return 'foo bar'

# now I expect 'foo bar'. Not happening.
print(g(*args))
#>>> bar


# let's reverse the argument order:
@cachier()
def g(bars, foo):
    return 'foo bar'

# now I also expect 'foo bar'. No luck.
print(g(*args))
#>>> bar

```

It seems as the cache is not invalidated when the arguments change here although I would expect that. Do you agree? I am using cachier 1.5.0.

**Comment by shaypal5** [comment] 2021-09-17 11:38
This is an often-requested feature which is way more complex than it seems initially.

This was discussed in the following issues:
#9 
#34

And attempted in two separate pull requests:
#17 , which was merged and then had to be reverted due to issues #18 and #19
#35 , which was rejected for the same reasons.

I would absolutely LOVE it if you would like to make a contribution to help with this feature. If you would like  to do so, however, you would have to start with getting up-to-date with past discussions, issues and attempted contributions. Read up and let me know what you think.

Finally, I'm closing this issue as it's a duplicate of #34 .
Please continue all related discussion there.

Cheers,
Shay

**Closed by shaypal5** 2021-09-17 11:38 UTC
