### ISSUE TITLE
Refresh cache when the function code source change

### ISSUE THREAD

**Issue by abocquet** [shaypal5/cachier#88] opened 2022-05-03 09:55 UTC
Currently, the cache is loaded even if the function code has changed. For prototyping purposes, it would be great to have the possibility to reload the cache on source code change.

Example : 
```python
from cachier import cachier

@cachier()
def f(x):
    print("This will print once")
    return x + 3
print(f(0)) # -> 3
```
will put the result of `f(0)` in cache for instance. But, when changing `3` to `4` : 
```python
@cachier()
def f(x):
    print("This will not be printed unless cache is invalidated manually")
    return x + 4
print(f(0))  # -> 3 
```

TBD :
- This behavior could be default, or enabled with a parameter `reload_on_source_change`
- Should it refresh only when the body of the function changes (easy) or recursively on any change of a function called in the body (harder, maybe not necessary)

**Comment by shaypal5** [comment] 2022-05-03 10:41
This is a duplicate of #34 , and is often discussed.

Please see the last comment there for the history of attempts to add this feature. :)

https://github.com/shaypal5/cachier/issues/34

**Closed by shaypal5** 2022-05-03 10:41 UTC
